development:
  adapter: postgresql
  database: samuel_dev
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: samuel_prod
  host: # fill this in with your hostname
  pool: 5
  timeout: 5000
